
c00d1a76ed18af10282cdf6c022aa2c180c9d944
90753d529c466887717a7f0c782d0f4a9fdbd8f2
###
# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений

GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token c00d1a76ed18af10282cdf6c022aa2c180c9d944

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/18/
Content-Type: application/json
Authorization: Token c00d1a76ed18af10282cdf6c022aa2c180c9d944

{
  "description": "Продано"
}

# {
#   "status": "OPEN"
# }

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-25
Content-Type: application/json

###

GET {{baseUrl}}/advertisements/?updated_at_before=2022-10-22
Content-Type: application/json

###

DELETE {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token 90753d529c466887717a7f0c782d0f4a9fdbd8f2